[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
postit_solana = "HrtnALGpHz67cyodA3tNU6axrjp3WVshXfXDtambhKBM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/codespace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
